[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.34"
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
anvil = "http://127.0.0.1:9955"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
